RC_SITE_KEY = '6LcEoOEUAAAAAGBG-OhwFO1W2kPKIGZivUewOXNy'
RC_SECRET_KEY = '6LcEoOEUAAAAACFBdgJ0FdyJNFa70GCduPRfAFYk'


class Config(object):
    # SECRET_KEY IS A RANDOM STRING FOR CSFR AVOIDANCE
    SECRET_KEY = '78asdfuGeasdfasdfVDF9asdf1MVE'
    SECURITY_PASSWORD_SALT = "e7asdf4asdf895b1540asdfa464fbd7"
    RECAPTCHA_PUBLIC_KEY = RC_SITE_KEY
    RECAPTCHA_PRIVATE_KEY = RC_SECRET_KEY